CREATE TABLE `iknow`.`ik_data` (
  `code` varchar(6) NOT NULL,
  `date` varchar(10) NOT NULL,
  `open` double NOT NULL,
  `high` double NOT NULL,
  `low` double NOT NULL,
  `close` double NOT NULL,
  `volh` double NOT NULL,
  `volwy` double NOT NULL,
  PRIMARY KEY (`code`,`date`),
  KEY `cd` (`code`),
  KEY `dt` (`date`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE `iknow`.`ik_attr` (
  `code` varchar(6) NOT NULL,
  `date` varchar(10) NOT NULL,
  `hb` int(1) NOT NULL,
  `lb` int(1) NOT NULL,
  `kline` int(1) NOT NULL,
  `csrc` double NOT NULL,
  `zdf` double NOT NULL,
  `k` double NOT NULL,
  `d` double NOT NULL,
  `mid` double NOT NULL,
  `std` double NOT NULL,
  `emaf` double NOT NULL,
  `emas` double NOT NULL,
  `diff` double NOT NULL,
  `dea` double NOT NULL,
  `macd` double NOT NULL,
  `ma5` double NOT NULL,
  `ma10` double NOT NULL,
  `ma30` double NOT NULL,
  `ma60` double NOT NULL,
  `vol3` double NOT NULL,
  `vol5` double NOT NULL,
  `vol10` double NOT NULL,
  `vol20` double NOT NULL,
  PRIMARY KEY (`code`,`date`),
  KEY `cd` (`code`),
  KEY `dt` (`date`),
  KEY `dth` (`hb`,`date`),
  KEY `dtl` (`lb`,`date`),
  KEY `dtk` (`date`,`kline`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE `iknow`.`ik_deri` (
  `code` varchar(6) NOT NULL,
  `date` varchar(10) NOT NULL,
  `fv` int(1) NOT NULL,
  `kfv` int(1) NOT NULL,
  `bfv` int(1) NOT NULL,
  `mfv` int(1) NOT NULL,
  PRIMARY KEY (`code`,`date`),
  KEY `dt` (`date`),
  KEY `cd` (`code`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE `iknow`.`ik_feature` (
  `code` varchar(6) NOT NULL,
  `date` varchar(10) NOT NULL,
  `vr` double NOT NULL,
  `fv4` varchar(4) NOT NULL,
  `nextdate` varchar(10) NOT NULL,
  `nextfv` int(1) NOT NULL,
  `openr` double NOT NULL,
  `highr` double NOT NULL,
  `lowr` double NOT NULL,
  `closer` double NOT NULL,
  `nextfv4` varchar(4) NOT NULL,
  PRIMARY KEY (`code`,`date`),
  KEY `fv4` (`fv4`,`vr`,`nextfv`,`highr`,`lowr`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE `iknow`.`ik_next` (
  `code` varchar(6) NOT NULL,
  `date` varchar(10) NOT NULL,
  `fv4` varchar(4) NOT NULL,
  `fv4cnt` int(1) NOT NULL,
  `fv4p1` double NOT NULL,
  `fv4p2` double NOT NULL,
  `fv4p3` double NOT NULL,
  `fv4p4` double NOT NULL,
  `fv4p5` double NOT NULL,
  `fv4p6` double NOT NULL,
  `fv4p7` double NOT NULL,
  `fv4p8` double NOT NULL,
  PRIMARY KEY (`code`,`date`),
  KEY `dt` (`date`),
  KEY `cd` (`code`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE `ik_rt` (
  `code` varchar(6) NOT NULL,
  `name` varchar(20) NOT NULL,
  `industry` varchar(20) NOT NULL,
  `watch` int(1) NOT NULL DEFAULT '0',
  `rtwatch` int(1) NOT NULL,
  `basedate` varchar(10) NOT NULL DEFAULT '0',
  `timestamp` varchar(20) NOT NULL,
  `high8` double NOT NULL DEFAULT '0',
  `low8` double NOT NULL DEFAULT '0',
  `laststd` double NOT NULL DEFAULT '0',
  `s4` double NOT NULL DEFAULT '0',
  `s9` double NOT NULL DEFAULT '0',
  `s29` double NOT NULL DEFAULT '0',
  `s59` double NOT NULL DEFAULT '0',
  `fv3` varchar(3) NOT NULL DEFAULT '0',
  `date` varchar(10) NOT NULL DEFAULT '0',
  `time` varchar(10) NOT NULL DEFAULT '0',
  `zdf` double NOT NULL DEFAULT '0',
  `csrc` double NOT NULL DEFAULT '0',
  `volwy` double NOT NULL DEFAULT '0',
  `vr` double NOT NULL DEFAULT '0',
  `close` double NOT NULL DEFAULT '0',
  `ma5` double NOT NULL DEFAULT '0',
  `ma10` double NOT NULL DEFAULT '0',
  `ma20` double NOT NULL DEFAULT '0',
  `ma30` double NOT NULL DEFAULT '0',
  `ma60` double NOT NULL DEFAULT '0',
  `fv4` varchar(4) NOT NULL DEFAULT '0',
  `fv4cnt` int(1) NOT NULL DEFAULT '0',
  `fv4p1` double NOT NULL DEFAULT '0',
  `fv4p2` double NOT NULL DEFAULT '0',
  `fv4p3` double NOT NULL DEFAULT '0',
  `fv4p4` double NOT NULL DEFAULT '0',
  `fv4p5` double NOT NULL DEFAULT '0',
  `fv4p6` double NOT NULL DEFAULT '0',
  `fv4p7` double NOT NULL DEFAULT '0',
  `fv4p8` double NOT NULL DEFAULT '0',
  `rttimestamp` varchar(20) NOT NULL,
  PRIMARY KEY (`code`),
  KEY `wt` (`watch`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

